---
- name: Ansible Dynamic Inventory for AWS Routers
  hosts: localhost
  gather_facts: false
  connection: network_cli

  tasks:
    - name: Create In-memory Ansible Inventory
      add_host:
        name: edge
        groups: edge_routers
        ansible_user: cisco123
        ansible_ssh_pass: cisco123
        ansible_become: yes
        ansible_become_method: enable
        ansible_become_password: cisco123
        ansible_ssh_host: "{{ edge_public }}"
        ansible_network_os: cisco.ios.ios
        
- name: Configure Edge Cloud Router
  hosts: edge_routers
  gather_facts: false
  connection: network_cli

  tasks:
    - name: Create Edge Router Loopback0 Interface
      ios_config:
        lines:
        - ip address 192.168.0.x 255.255.255.255
        parents: interface Loopback0

    - name: Create Edge Router EIGRP Routing Process
      ios_config:
        lines:
        - network 192.168.0.x 0.0.0.0
        - no auto-summary
        parents: router eigrp 100
