---
- name: Ansible Dynamic Inventory for AWS Routers
  hosts: localhost
  gather_facts: false
  connection: network_cli

  tasks:
    - name: Create In-memory Ansible Inventory
      add_host:
        name: edge
        groups: edge_routers
        ansible_user: cisco123
        ansible_ssh_pass: cisco123
        ansible_become: yes
        ansible_become_method: enable
        ansible_become_password: cisco123
        ansible_ssh_host: "{{ edge_public }}"
        ansible_network_os: cisco.ios.ios
        
    - name: Create In-Memory Headend Inventory
      add_host:
        name: headend
        groups: headend_routers
        ansible_user: cisco123
        ansible_ssh_pass: cisco123
        ansible_become: yes
        ansible_become_method: enable
        ansible_become_password: cisco123
        ansible_ssh_host: "{{ headend_public }}"
        ansible_network_os: cisco.ios.ios
        
- name: Wait for Router to be accessible
  hosts: edge_routers
  gather_facts: false
  connection: network_cli

  tasks:
    - name: Wait for device to be reachable
      wait_for:
        host: "{{ edge_public }}"
        port: 22
       
- name: Configure Edge Cloud Router
  hosts: edge_routers
  gather_facts: false
  connection: network_cli

  tasks:
    - name: Wait for Authentication to be Available
      pause:
        seconds: 30

    - name: Create Edge Router Loopback0 Interface
      ios_config:
        lines:
        - ip address 192.168.0.x 255.255.255.255
        parents: interface Loopback0

    - name: Create Edge Router Tunnelx Interface
      ios_config:
        lines:
        - ip address 172.16.0.x 255.255.255.252
        - ip mtu 1400
        - ip tcp adjust-mss 1360
        - tunnel source GigabitEthernet1
        - tunnel destination {{ headend_private }}
        parents: interface Tunnelx

    - name: Configure Edge Router EIGRP Routing Process
      ios_config:
        lines:
        - network 172.16.0.x 0.0.0.3
        - network 192.168.0.x 0.0.0.0
        - no auto-summary
        parents: router eigrp 100
        
- name: Configure Headend Cloud Router
  hosts: headend_routers
  gather_facts: false
  connection: network_cli

  tasks:
    - name: Configure Headend Router Tunnelx Interface
      ios_config:
        lines:
        - ip address 172.16.0.x 255.255.255.252
        - ip mtu 1400
        - ip tcp adjust-mss 1360
        - tunnel source GigabitEthernet1
        - tunnel destination {{ edge_private }}
        parents: interface Tunnelx

    - name: Configure Headend Cloud Router EIGRP Routing Process
      ios_config:
        lines:
        - network 172.16.0.x 0.0.0.3
        parents: router eigrp 100
